"""empty message

Revision ID: 12251d6ec884
Revises: 
Create Date: 2018-08-05 11:21:24.439525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12251d6ec884'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cal123asdas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterpriseagreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=True),
    sa.Column('min_periods', sa.Integer(), nullable=True),
    sa.Column('max_periods', sa.Integer(), nullable=True),
    sa.Column('max_periods_overtime', sa.Integer(), nullable=True),
    sa.Column('wage', sa.Float(), nullable=True),
    sa.Column('wage_overtime', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.Column('agreement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agreement'], ['enterpriseagreement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('schedule_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('requirement', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['period'], ['period.id'], ),
    sa.ForeignKeyConstraint(['requirement'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=True),
    sa.Column('shift_length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['start_period'], ['period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee', sa.Integer(), nullable=False),
    sa.Column('shift', sa.Integer(), nullable=False),
    sa.Column('preference_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['shift'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee', sa.Integer(), nullable=False),
    sa.Column('shift', sa.Integer(), nullable=False),
    sa.Column('skill', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['shift'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['skill'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('shift', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['period'], ['period.id'], ),
    sa.ForeignKeyConstraint(['shift'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.Integer(), nullable=False),
    sa.Column('employee', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['skill'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_assignment')
    op.drop_table('shift_periods')
    op.drop_table('schedule_allocation')
    op.drop_table('preference')
    op.drop_table('shift')
    op.drop_table('schedule_requirement')
    op.drop_table('employee')
    op.drop_table('skill')
    op.drop_table('period')
    op.drop_table('enterpriseagreement')
    op.drop_table('cal123asdas')
    # ### end Alembic commands ###
