"""empty message

Revision ID: 6950b0ae09a6
Revises: ed606cc52034
Create Date: 2018-10-13 15:52:36.067713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6950b0ae09a6'
down_revision = 'ed606cc52034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('employee', sa.Column('emergency_contact', sa.String(), nullable=True))
    op.add_column('employee', sa.Column('emergency_contact_phone_no', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('emergency_contact_relationship', sa.String(), nullable=True))
    op.add_column('employee', sa.Column('financial_tax_file_number', sa.String(), nullable=True))
    op.add_column('employee', sa.Column('first_name', sa.String(length=24), nullable=True))
    op.add_column('employee', sa.Column('gender', sa.String(length=1), nullable=True))
    op.add_column('employee', sa.Column('last_name', sa.String(length=24), nullable=True))
    op.add_column('employee', sa.Column('phone_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'phone_no')
    op.drop_column('employee', 'last_name')
    op.drop_column('employee', 'gender')
    op.drop_column('employee', 'first_name')
    op.drop_column('employee', 'financial_tax_file_number')
    op.drop_column('employee', 'emergency_contact_relationship')
    op.drop_column('employee', 'emergency_contact_phone_no')
    op.drop_column('employee', 'emergency_contact')
    op.drop_column('employee', 'date_of_birth')
    # ### end Alembic commands ###
