"""empty message

Revision ID: 99ec5f66b096
Revises: 00c352b63351
Create Date: 2018-06-11 22:52:18.135897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ec5f66b096'
down_revision = '00c352b63351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preference', sa.Column('employee', sa.Integer(), nullable=False))
    op.add_column('preference', sa.Column('preference_level', sa.Integer(), nullable=True))
    op.add_column('preference', sa.Column('shift', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'preference', 'employee', ['employee'], ['id'])
    op.create_foreign_key(None, 'preference', 'shift', ['shift'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preference', type_='foreignkey')
    op.drop_constraint(None, 'preference', type_='foreignkey')
    op.drop_column('preference', 'shift')
    op.drop_column('preference', 'preference_level')
    op.drop_column('preference', 'employee')
    # ### end Alembic commands ###
